/**
 * Qello API
 * REST API <!-- <br/> <br/> <a href='#' id='' onclick='showRestJSONObjectsHttpAPI();'>Qello API (JSON Requests)</a> -->
 *
 * OpenAPI spec version: 1.1.4
 * Contact: contact@qello.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.QelloApi) {
      root.QelloApi = {};
    }
    root.QelloApi.Device = factory(root.QelloApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Device model module.
   * @module model/Device
   * @version 1.1.4
   */

  /**
   * Constructs a new <code>Device</code>.
   * @alias module:model/Device
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>Device</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Device} obj Optional instance to populate.
   * @return {module:model/Device} The populated <code>Device</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('device_name_id')) {
        obj['device_name_id'] = ApiClient.convertToType(data['device_name_id'], 'Number');
      }
      if (data.hasOwnProperty('push_id')) {
        obj['push_id'] = ApiClient.convertToType(data['push_id'], 'String');
      }
      if (data.hasOwnProperty('device_id')) {
        obj['device_id'] = ApiClient.convertToType(data['device_id'], 'String');
      }
      if (data.hasOwnProperty('is_first')) {
        obj['is_first'] = ApiClient.convertToType(data['is_first'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} device_name_id
   */
  exports.prototype['device_name_id'] = undefined;
  /**
   * @member {String} push_id
   */
  exports.prototype['push_id'] = undefined;
  /**
   * @member {String} device_id
   */
  exports.prototype['device_id'] = undefined;
  /**
   * @member {Number} is_first
   */
  exports.prototype['is_first'] = undefined;



  return exports;
}));


