/**
 * Qello API
 * REST API <!-- <br/> <br/> <a href='#' id='' onclick='showRestJSONObjectsHttpAPI();'>Qello API (JSON Requests)</a> -->
 *
 * OpenAPI spec version: 1.1.4
 * Contact: contact@qello.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AssetSearchItem', 'model/TagSearchItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AssetSearchItem'), require('./TagSearchItem'));
  } else {
    // Browser globals (root is window)
    if (!root.QelloApi) {
      root.QelloApi = {};
    }
    root.QelloApi.SearchAssetsObject = factory(root.QelloApi.ApiClient, root.QelloApi.AssetSearchItem, root.QelloApi.TagSearchItem);
  }
}(this, function(ApiClient, AssetSearchItem, TagSearchItem) {
  'use strict';




  /**
   * The SearchAssetsObject model module.
   * @module model/SearchAssetsObject
   * @version 1.1.4
   */

  /**
   * Constructs a new <code>SearchAssetsObject</code>.
   * @alias module:model/SearchAssetsObject
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>SearchAssetsObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchAssetsObject} obj Optional instance to populate.
   * @return {module:model/SearchAssetsObject} The populated <code>SearchAssetsObject</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Episodes')) {
        obj['Episodes'] = ApiClient.convertToType(data['Episodes'], [AssetSearchItem]);
      }
      if (data.hasOwnProperty('Shows')) {
        obj['Shows'] = ApiClient.convertToType(data['Shows'], [AssetSearchItem]);
      }
      if (data.hasOwnProperty('Seasons')) {
        obj['Seasons'] = ApiClient.convertToType(data['Seasons'], [AssetSearchItem]);
      }
      if (data.hasOwnProperty('Topics')) {
        obj['Topics'] = ApiClient.convertToType(data['Topics'], [TagSearchItem]);
      }
      if (data.hasOwnProperty('Curated')) {
        obj['Curated'] = ApiClient.convertToType(data['Curated'], [TagSearchItem]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/AssetSearchItem>} Episodes
   */
  exports.prototype['Episodes'] = undefined;
  /**
   * @member {Array.<module:model/AssetSearchItem>} Shows
   */
  exports.prototype['Shows'] = undefined;
  /**
   * @member {Array.<module:model/AssetSearchItem>} Seasons
   */
  exports.prototype['Seasons'] = undefined;
  /**
   * @member {Array.<module:model/TagSearchItem>} Topics
   */
  exports.prototype['Topics'] = undefined;
  /**
   * @member {Array.<module:model/TagSearchItem>} Curated
   */
  exports.prototype['Curated'] = undefined;



  return exports;
}));


