/**
 * Qello API
 * REST API <!-- <br/> <br/> <a href='#' id='' onclick='showRestJSONObjectsHttpAPI();'>Qello API (JSON Requests)</a> -->
 *
 * OpenAPI spec version: 1.1.4
 * Contact: contact@qello.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Device', 'model/Profile', 'model/Session', 'model/Subscription', 'model/User'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Device'), require('./Profile'), require('./Session'), require('./Subscription'), require('./User'));
  } else {
    // Browser globals (root is window)
    if (!root.QelloApi) {
      root.QelloApi = {};
    }
    root.QelloApi.SessionRecord = factory(root.QelloApi.ApiClient, root.QelloApi.Device, root.QelloApi.Profile, root.QelloApi.Session, root.QelloApi.Subscription, root.QelloApi.User);
  }
}(this, function(ApiClient, Device, Profile, Session, Subscription, User) {
  'use strict';




  /**
   * The SessionRecord model module.
   * @module model/SessionRecord
   * @version 1.1.4
   */

  /**
   * Constructs a new <code>SessionRecord</code>.
   * @alias module:model/SessionRecord
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>SessionRecord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SessionRecord} obj Optional instance to populate.
   * @return {module:model/SessionRecord} The populated <code>SessionRecord</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('session')) {
        obj['session'] = Session.constructFromObject(data['session']);
      }
      if (data.hasOwnProperty('user')) {
        obj['user'] = User.constructFromObject(data['user']);
      }
      if (data.hasOwnProperty('profile')) {
        obj['profile'] = Profile.constructFromObject(data['profile']);
      }
      if (data.hasOwnProperty('device')) {
        obj['device'] = Device.constructFromObject(data['device']);
      }
      if (data.hasOwnProperty('subscription')) {
        obj['subscription'] = Subscription.constructFromObject(data['subscription']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Session} session
   */
  exports.prototype['session'] = undefined;
  /**
   * @member {module:model/User} user
   */
  exports.prototype['user'] = undefined;
  /**
   * @member {module:model/Profile} profile
   */
  exports.prototype['profile'] = undefined;
  /**
   * @member {module:model/Device} device
   */
  exports.prototype['device'] = undefined;
  /**
   * @member {module:model/Subscription} subscription
   */
  exports.prototype['subscription'] = undefined;



  return exports;
}));


