/**
 * Qello API
 * REST API <!-- <br/> <br/> <a href='#' id='' onclick='showRestJSONObjectsHttpAPI();'>Qello API (JSON Requests)</a> -->
 *
 * OpenAPI spec version: 1.1.4
 * Contact: contact@qello.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AssetsResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AssetsResult'));
  } else {
    // Browser globals (root is window)
    if (!root.QelloApi) {
      root.QelloApi = {};
    }
    root.QelloApi.AssetsApi = factory(root.QelloApi.ApiClient, root.QelloApi.AssetsResult);
  }
}(this, function(ApiClient, AssetsResult) {
  'use strict';

  /**
   * Assets service.
   * @module api/AssetsApi
   * @version 1.1.4
   */

  /**
   * Constructs a new AssetsApi. 
   * @alias module:api/AssetsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getAssets operation.
     * @callback module:api/AssetsApi~getAssetsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AssetsResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Asset/Assets
     * Get Single Asset by Id or Multiple Assets by filters
     * @param {String} token Token
     * @param {Object} opts Optional parameters
     * @param {Number} opts.id Asset Id
     * @param {Number} opts.limit Limit
     * @param {Number} opts.offset Offset
     * @param {String} opts.type Type - Audio, Video
     * @param {String} opts.classification Classification
     * @param {String} opts.order Order (Field to Order By)
     * @param {module:model/String} opts.orderType Order Type (ASC,DESC)
     * @param {Boolean} opts.extended Extended Mode (to include or not detailed childern/parent info)
     * @param {Number} opts.searchId0 Search by Tag Id
     * @param {Number} opts.searchId1 Search by Tag Id
     * @param {Number} opts.searchId2 Search by Tag Id
     * @param {String} opts.searchTag0 Search by Tag Name
     * @param {String} opts.searchTag1 Search by Tag Name
     * @param {String} opts.searchTag2 Search by Tag Name
     * @param {String} opts.searchMetaTitle1 Search by Meta Title Name
     * @param {String} opts.searchMetaTitle2 Search by Meta Title Name
     * @param {String} opts.searchMetaCountry1 Search by Meta Country Name
     * @param {String} opts.searchMetaYear1 Search by Meta year
     * @param {Number} opts.collectionId Collection Id if type is set to &#39;Custom&#39;
     * @param {module:model/String} opts.collectionType Collection Type (for predefined types [&#39;Favorites&#39;, &#39;WatchLater&#39;] or &#39;Custom&#39;)
     * @param {module:api/AssetsApi~getAssetsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AssetsResult}
     */
    this.getAssets = function(token, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'token' is set
      if (token == undefined || token == null) {
        throw new Error("Missing the required parameter 'token' when calling getAssets");
      }


      var pathParams = {
      };
      var queryParams = {
        'token': token,
        'id': opts['id'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'type': opts['type'],
        'classification': opts['classification'],
        'order': opts['order'],
        'order_type': opts['orderType'],
        'extended': opts['extended'],
        'search[id][0]': opts['searchId0'],
        'search[id][1]': opts['searchId1'],
        'search[id][2]': opts['searchId2'],
        'search[tag][0]': opts['searchTag0'],
        'search[tag][1]': opts['searchTag1'],
        'search[tag][2]': opts['searchTag2'],
        'search[meta][title][1]': opts['searchMetaTitle1'],
        'search[meta][title][2]': opts['searchMetaTitle2'],
        'search[meta][country][1]': opts['searchMetaCountry1'],
        'search[meta][year][1]': opts['searchMetaYear1'],
        'collection_id': opts['collectionId'],
        'collection_type': opts['collectionType']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/api+json', 'application/api+xml', 'application/api+jsonp'];
      var returnType = AssetsResult;

      return this.apiClient.callApi(
        '/assets/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
