/**
 * Qello API
 * REST API <!-- <br/> <br/> <a href='#' id='' onclick='showRestJSONObjectsHttpAPI();'>Qello API (JSON Requests)</a> -->
 *
 * OpenAPI spec version: 1.1.4
 * Contact: contact@qello.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AvatarsResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AvatarsResult'));
  } else {
    // Browser globals (root is window)
    if (!root.QelloApi) {
      root.QelloApi = {};
    }
    root.QelloApi.AvatarsApi = factory(root.QelloApi.ApiClient, root.QelloApi.AvatarsResult);
  }
}(this, function(ApiClient, AvatarsResult) {
  'use strict';

  /**
   * Avatars service.
   * @module api/AvatarsApi
   * @version 1.1.4
   */

  /**
   * Constructs a new AvatarsApi. 
   * @alias module:api/AvatarsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getAvatars operation.
     * @callback module:api/AvatarsApi~getAvatarsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AvatarsResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Avatars
     * Get Avatars List
     * @param {String} token Token
     * @param {Object} opts Optional parameters
     * @param {Number} opts.id Avatar Id
     * @param {module:api/AvatarsApi~getAvatarsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AvatarsResult}
     */
    this.getAvatars = function(token, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'token' is set
      if (token == undefined || token == null) {
        throw new Error("Missing the required parameter 'token' when calling getAvatars");
      }


      var pathParams = {
      };
      var queryParams = {
        'token': token,
        'id': opts['id']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/api+json', 'application/api+xml', 'application/api+jsonp'];
      var returnType = AvatarsResult;

      return this.apiClient.callApi(
        '/avatars/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
