/**
 * Qello API
 * REST API <!-- <br/> <br/> <a href='#' id='' onclick='showRestJSONObjectsHttpAPI();'>Qello API (JSON Requests)</a> -->
 *
 * OpenAPI spec version: 1.1.4
 * Contact: contact@qello.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.QelloApi) {
      root.QelloApi = {};
    }
    root.QelloApi.BrokerApi = factory(root.QelloApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Broker service.
   * @module api/BrokerApi
   * @version 1.1.4
   */

  /**
   * Constructs a new BrokerApi. 
   * @alias module:api/BrokerApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getSubtitles operation.
     * @callback module:api/BrokerApi~getSubtitlesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Subtitles in specific format
     * Get Subtitles in specific format
     * @param {String} token Token
     * @param {Number} assetId Asset Id
     * @param {Object} opts Optional parameters
     * @param {Number} opts.format Preferred Format
     * @param {Number} opts.lang Preferred Lang
     * @param {module:api/BrokerApi~getSubtitlesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getSubtitles = function(token, assetId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'token' is set
      if (token == undefined || token == null) {
        throw new Error("Missing the required parameter 'token' when calling getSubtitles");
      }

      // verify the required parameter 'assetId' is set
      if (assetId == undefined || assetId == null) {
        throw new Error("Missing the required parameter 'assetId' when calling getSubtitles");
      }


      var pathParams = {
      };
      var queryParams = {
        'token': token,
        'asset_id': assetId,
        'format': opts['format'],
        'lang': opts['lang']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['binary/octet-stream', 'application/xml'];
      var returnType = null;

      return this.apiClient.callApi(
        '/broker/subtitles/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getVideo operation.
     * @callback module:api/BrokerApi~getVideoCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Broker - Returns Playlist or MP4 Url
     * Broker - returns media file/playlist for an asset. On success the result is &#39;application/api+x-mpegurl&#39; otherwise json/xml
     * @param {String} token Token
     * @param {Number} assetId Asset Id
     * @param {Object} opts Optional parameters
     * @param {String} opts.codec Preferred Codec - HLS, MP4, HLS-WEB, etc..
     * @param {Number} opts.bandwidth Preferred bandwidth if no codec specified
     * @param {module:api/BrokerApi~getVideoCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getVideo = function(token, assetId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'token' is set
      if (token == undefined || token == null) {
        throw new Error("Missing the required parameter 'token' when calling getVideo");
      }

      // verify the required parameter 'assetId' is set
      if (assetId == undefined || assetId == null) {
        throw new Error("Missing the required parameter 'assetId' when calling getVideo");
      }


      var pathParams = {
      };
      var queryParams = {
        'token': token,
        'asset_id': assetId,
        'codec': opts['codec'],
        'bandwidth': opts['bandwidth']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/api+x-mpegurl'];
      var returnType = null;

      return this.apiClient.callApi(
        '/broker/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
