/**
 * Qello API
 * REST API <!-- <br/> <br/> <a href='#' id='' onclick='showRestJSONObjectsHttpAPI();'>Qello API (JSON Requests)</a> -->
 *
 * OpenAPI spec version: 1.1.4
 * Contact: contact@qello.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SearchResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/SearchResult'));
  } else {
    // Browser globals (root is window)
    if (!root.QelloApi) {
      root.QelloApi = {};
    }
    root.QelloApi.ContentsearchApi = factory(root.QelloApi.ApiClient, root.QelloApi.SearchResult);
  }
}(this, function(ApiClient, SearchResult) {
  'use strict';

  /**
   * Contentsearch service.
   * @module api/ContentsearchApi
   * @version 1.1.4
   */

  /**
   * Constructs a new ContentsearchApi. 
   * @alias module:api/ContentsearchApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the contentsearch operation.
     * @callback module:api/ContentsearchApi~contentsearchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SearchResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search for Assets
     * Search for assets
     * @param {String} token Token
     * @param {String} term Term
     * @param {Number} limit Limit
     * @param {Object} opts Optional parameters
     * @param {Number} opts.offset Offset
     * @param {module:api/ContentsearchApi~contentsearchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SearchResult}
     */
    this.contentsearch = function(token, term, limit, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'token' is set
      if (token == undefined || token == null) {
        throw new Error("Missing the required parameter 'token' when calling contentsearch");
      }

      // verify the required parameter 'term' is set
      if (term == undefined || term == null) {
        throw new Error("Missing the required parameter 'term' when calling contentsearch");
      }

      // verify the required parameter 'limit' is set
      if (limit == undefined || limit == null) {
        throw new Error("Missing the required parameter 'limit' when calling contentsearch");
      }


      var pathParams = {
      };
      var queryParams = {
        'token': token,
        'term': term,
        'limit': limit,
        'offset': opts['offset']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/api+json', 'application/api+xml', 'application/api+jsonp'];
      var returnType = SearchResult;

      return this.apiClient.callApi(
        '/contentsearch/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
