/**
 * Qello API
 * REST API <!-- <br/> <br/> <a href='#' id='' onclick='showRestJSONObjectsHttpAPI();'>Qello API (JSON Requests)</a> -->
 *
 * OpenAPI spec version: 1.1.4
 * Contact: contact@qello.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.QelloApi) {
      root.QelloApi = {};
    }
    root.QelloApi.ScheduleApi = factory(root.QelloApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Schedule service.
   * @module api/ScheduleApi
   * @version 1.1.4
   */

  /**
   * Constructs a new ScheduleApi. 
   * @alias module:api/ScheduleApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the schedule operation.
     * @callback module:api/ScheduleApi~scheduleCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Program Schedule for Channels
     * Program Schedule for Channels
     * @param {String} token Token
     * @param {Object} opts Optional parameters
     * @param {Number} opts.channelId Channel Id
     * @param {Number} opts.visible visible
     * @param {String} opts.startTime Start Time
     * @param {Number} opts.interval Interval (default to 600)
     * @param {module:api/ScheduleApi~scheduleCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.schedule = function(token, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'token' is set
      if (token == undefined || token == null) {
        throw new Error("Missing the required parameter 'token' when calling schedule");
      }


      var pathParams = {
      };
      var queryParams = {
        'token': token,
        'channel_id': opts['channelId'],
        'visible': opts['visible'],
        'startTime': opts['startTime'],
        'interval': opts['interval']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/api+json', 'application/api+xml', 'application/api+jsonp'];
      var returnType = null;

      return this.apiClient.callApi(
        '/schedule/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
