/**
 * Qello API
 * REST API <!-- <br/> <br/> <a href='#' id='' onclick='showRestJSONObjectsHttpAPI();'>Qello API (JSON Requests)</a> -->
 *
 * OpenAPI spec version: 1.1.4
 * Contact: contact@qello.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QelloApi);
  }
}(this, function(expect, QelloApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QelloApi.ProfileTokenObject();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProfileTokenObject', function() {
    it('should create an instance of ProfileTokenObject', function() {
      // uncomment below and update the code to test ProfileTokenObject
      //var instane = new QelloApi.ProfileTokenObject();
      //expect(instance).to.be.a(QelloApi.ProfileTokenObject);
    });

    it('should have the property profileToken (base name: "profile_token")', function() {
      // uncomment below and update the code to test the property profileToken
      //var instane = new QelloApi.ProfileTokenObject();
      //expect(instance).to.be();
    });

    it('should have the property profileId (base name: "profile_id")', function() {
      // uncomment below and update the code to test the property profileId
      //var instane = new QelloApi.ProfileTokenObject();
      //expect(instance).to.be();
    });

  });

}));
